INSERT INTO MOVIE VALUES (1, 'The latest installment in mission impossible franchise', 'MISSION_IMPOSSIBLE : GHOST RECKON',0,2012);
INSERT INTO MOVIE VALUES (2, 'New age science fiction', 'INTERSTELLAR',0,2011);
INSERT INTO MOVIE VALUES (3, 'Its a drama-comedy series', 'LOVE STRUCK',0,2019);
INSERT INTO MOVIE VALUES (4, 'New age science fiction', 'GODSPEED',0,2022);
INSERT INTO MOVIE VALUES (5, 'Drama plus motivating', 'Hey! Phil',0,2022);

INSERT INTO USER VALUES (1, 'Srijan','roychoudhurysrijan442@gmail.com');
INSERT INTO USER VALUES (2, 'David','abc@gmail.com');

INSERT INTO CINEMA VALUES(1,'Gwariahat road, under bridge pass','PVR CINEMAS','Ganguly Bagan',2);
INSERT INTO CINEMA VALUES(2,'Garia road, crossing 1-14th','SHINING SCREENS CINEMAS','Garia BT',1);
INSERT INTO CINEMA VALUES(3,'Garden street, jabalipur','RUPASHI CINEMAS','Lake Gardens',1);
INSERT INTO CINEMA VALUES(4,'Sonai Kolkata second lane','BALAKA CINEMAS','South Eastern Railway',1);
INSERT INTO CINEMA VALUES(5,'Ramnagar road no 1','IOPEX CINEMAS','Agartala',1);


INSERT INTO CINEMA_HALL VALUES(1,1,1,11);
INSERT INTO CINEMA_HALL VALUES(2,1,2,12);
INSERT INTO CINEMA_HALL VALUES(3,2,1,13);
INSERT INTO CINEMA_HALL VALUES(4,3,1,15);
INSERT INTO CINEMA_HALL VALUES(5,4,1,16);
INSERT INTO CINEMA_HALL VALUES(6,5,1,17);


INSERT INTO SCREENING VALUES(1,1,PARSEDATETIME('17-09-2022 18:47:52.69', 'dd-MM-yyyy hh:mm:ss.SS'),2);
INSERT INTO SCREENING VALUES(2,1,PARSEDATETIME('2-09-2022 20:47:52.69', 'dd-MM-yyyy hh:mm:ss.SS'),1);
INSERT INTO SCREENING VALUES(3,2,PARSEDATETIME('21-09-2022 13:47:52.69', 'dd-MM-yyyy hh:mm:ss.SS'),3);
INSERT INTO SCREENING VALUES(4,3,PARSEDATETIME('22-09-2022 12:47:52.69', 'dd-MM-yyyy hh:mm:ss.SS'),4);
INSERT INTO SCREENING VALUES(5,4,PARSEDATETIME('15-09-2022 11:47:52.69', 'dd-MM-yyyy hh:mm:ss.SS'),5);


